### ISSUE TITLE
Problem on the val/test step

### ISSUE THREAD

**Issue by KZGSK** [Markin-Wang/XProNet#1]
Hi ,Thank you for sharing your code. It's very nice work.
I'd like to ask you a few questions about CheXbert label. I think the label is obtained in the medical report. In the testing step, we didn't know it. But in the code, you use label ''output, _ = self.model(images, labels = labels, mode='sample')''.If I understand wrong, please let me know.
Thanks in avdance!

**Comment by Markin-Wang** [comment]
Hi, thanks for your interest.
We generate the pseudo labels for all subset,i.e., train/val/test sets according to the medical report.
The label information for the test set is not used in the training pharse, hence there is no test information leakage during the training. 
The inference follows the similar strategy as training where labels information is required to perform the cross-modal prototype querying and responding.

**Comment by KZGSK** [comment]
thanks for your reply.
I know there is no test information leakage during the training.
I mean in inference , we should not have medical report, so there should be no label. If I have an X-ray image without a report, how can I get the report through the code?
Thanks!

**Comment by Markin-Wang** [comment]
> thanks for your reply. I know there is no test information leakage during the training. I mean in inference , we should not have medical report, so there should be no label. If I have an X-ray image without a report, how can I get the report through the code? Thanks!

Yes, you are right.
Nonetheless, note that the lables are pseudo labels, and you can generate the pseudo labels by different ways, e.g., medical report or the pure image.
For example, if you have an X-ray image without report, you can train a visual extractor based on the labels in the train set,  and then predict the labels in the test set.
Hope this can solve your problem.

**Comment by KZGSK** [comment]
Thanks for your answer. I am gonna close this issue now.
