### ISSUE TITLE
Some questions about the DataParallel.

### ISSUE THREAD

**Issue by Liqq1** [Markin-Wang/XProNet#13]
Hi, thanks for your code!
You note in Readme that the code references R2GenCMN. 
However, there are some questions about the dataparallel code in R2GenCMN, as shown in [#issue](https://github.com/cuhksz-nlp/R2Gen/issues/2). 
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
(when checking argument for argument weight in method wrapper__cudnn_convolution)
```
And the code you provided is completely correct. Could you please tell me what modifications you have made? 
Thank you in advance!

**Comment by Otiss-pang** [comment]
> 

excuse me! I found the same problem as you, have you solved this problem? if you did, could you plz tell me how to solve it?

**Comment by Liqq1** [comment]
> excuse me! I found the same problem as you, have you solved this problem? if you did, could you plz tell me how to solve it?

Sorry, I haven't solved the problem yet 😢

**Comment by Otiss-pang** [comment]
> 
I used the DistributeDataParallel to build the parallel model, but some error happened. It seems that training procedure doesn't get quicker.
By the way, Do you kown how to caculate the CE metrics of mimic dataset? I used the Chexpert to extract the label of the generated reports, but I don't kown how to caculate the F1, Precision and recall.
Thanks!😄

**Comment by Markin-Wang** [comment]
> > 
> 
> I used the DistributeDataParallel to build the parallel model, but some error happened. It seems that training procedure doesn't get quicker. By the way, Do you kown how to caculate the CE metrics of mimic dataset? I used the Chexpert to extract the label of the generated reports, but I don't kown how to caculate the F1, Precision and recall. Thanks!😄

Hi, thank you for your interest to our work.

Hope the reply is not too late. We just update the XPRONet and now it supports the mixed-precision and DDP training. In addition, in the previous repo, the num_woker is set to 2 by default, this may cause the low training speed (tune it based on your machine). For the CE metrics, you can use Chexpert or CheXbert to label the generated reports, and use sklearn to calculate the F1, Precision and recall.

Hope this can help you figure out the problem.

**Comment by Markin-Wang** [comment]
@Liqq1 @Otiss-pang 

Hi, thank you for your interest to our work.

Hope the reply is not too late. We just update the XPRONet and now it supports the mixed-precision and DDP training. In addition, in the previous repo, the num_woker is set to 2 by default, this may cause the low training speed (tune it based on your machine). For the CE metrics, you can use Chexpert or CheXbert to label the generated reports, and use sklearn to calculate the F1, Precision and recall.

Hope this can help you figure out the problem.
