### ISSUE TITLE
I have questions about the dataset and the data loading code.

### ISSUE THREAD

**Issue by shenshaowei** [Markin-Wang/XProNet#22]
What are **init_prototypes.pt** and **labels_14.pickle** in the dataset? Why is the data format completely different from R2Gen, and these two files are not required for other R2Gen tasks. If I want to use my own dataset, how can I obtain these two files?

**Comment by Markin-Wang** [comment]
> What are **init_prototypes.pt** and **labels_14.pickle** in the dataset? Why is the data format completely different from R2Gen, and these two files are not required for other R2Gen tasks. If I want to use my own dataset, how can I obtain these two files?

Hi, thank you for your interest to our work. The function and details of these files are eloborated in our paper. Hence, I would like to recommend you read our paper first. Also, for your own dataset, you can follow the steps described in our paper and Readme file, e.g., pseudo label generation and cross-modal prototype initialization, to generate these two files, which is not complicated.

**Comment by shenshaowei** [comment]
"Which part of the code corresponds to pseudo label generation and cross-modal prototype initialization? Could you please provide some guidance? Thank you very much. Time is limited, and I would like to use your task as my baseline."

**Comment by shenshaowei** [comment]
"Which part of the code corresponds to pseudo label generation and cross-modal prototype initialization? Could you please provide some guidance? Thank you very much. Time is limited, and I would like to use your task as my baseline."
